language: python
branches:
  only:
  - gh-pages
addons:
  ssh_known_hosts: 62.210.170.125
before_deploy:
- openssl aes-256-cbc -K $encrypted_a11340138cd0_key -iv $encrypted_a11340138cd0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/* poils@62.210.170.125:/home/www/editor.vieuxsinge.com/.
  on:
    branch: gh-pages
before_install:
